
list = ["Janak" ,"Rohan", "Raj","Roy", "Bob", "Amitab" , "Janak"]
for a in list:
	if a == "Roy":
		print(a)
	else:
		pass

User_data = [{
  "id": 1,
  "first_name": "Geoffry",
  "last_name": "Frankcom",
  "email": "gfrankcom0@t.co",
  "gender": "Male",
  "ip_address": "4.174.187.155"
}, {
  "id": 2,
  "first_name": "Corrinne",
  "last_name": "Hold",
  "email": "chold1@vimeo.com",
  "gender": "Female",
  "ip_address": "13.134.232.41"
}, {
  "id": 3,
  "first_name": "Koenraad",
  "last_name": "Paolone",
  "email": "kpaolone2@hatena.ne.jp",
  "gender": "Male",
  "ip_address": "210.95.22.231"
}, {
  "id": 4,
  "first_name": "Annalee",
  "last_name": "Dearl",
  "email": "adearl3@mozilla.com",
  "gender": "Polygender",
  "ip_address": "230.57.213.101"
}, {
  "id": 5,
  "first_name": "Leshia",
  "last_name": "Bleas",
  "email": "lbleas4@jugem.jp",
  "gender": "Female",
  "ip_address": "60.108.72.103"
}, {
  "id": 6,
  "first_name": "Renaud",
  "last_name": "Oliver-Paull",
  "email": "roliverpaull5@vinaora.com",
  "gender": "Male",
  "ip_address": "80.172.227.252"
}, {
  "id": 7,
  "first_name": "Isaac",
  "last_name": "Prendiville",
  "email": "iprendiville6@oracle.com",
  "gender": "Male",
  "ip_address": "226.142.182.24"
}, {
  "id": 8,
  "first_name": "Ricoriki",
  "last_name": "Courson",
  "email": "rcourson7@devhub.com",
  "gender": "Male",
  "ip_address": "70.143.180.47"
}, {
  "id": 9,
  "first_name": "Trina",
  "last_name": "Wille",
  "email": "twille8@hugedomains.com",
  "gender": "Female",
  "ip_address": "198.63.244.63"
}, {
  "id": 10,
  "first_name": "Glynn",
  "last_name": "Plant",
  "email": "gplant9@xing.com",
  "gender": "Male",
  "ip_address": "162.110.15.143"
}, {
  "id": 11,
  "first_name": "Joceline",
  "last_name": "Senecaut",
  "email": "jsenecauta@chronoengine.com",
  "gender": "Female",
  "ip_address": "46.81.112.138"
}, {
  "id": 12,
  "first_name": "Brady",
  "last_name": "Mycroft",
  "email": "bmycroftb@microsoft.com",
  "gender": "Male",
  "ip_address": "137.121.64.24"
}, {
  "id": 13,
  "first_name": "Damien",
  "last_name": "McReynold",
  "email": "dmcreynoldc@va.gov",
  "gender": "Male",
  "ip_address": "179.172.174.89"
}, {
  "id": 14,
  "first_name": "Neely",
  "last_name": "Abercromby",
  "email": "nabercrombyd@feedburner.com",
  "gender": "Female",
  "ip_address": "197.36.162.54"
}, {
  "id": 15,
  "first_name": "Sibylla",
  "last_name": "Neate",
  "email": "sneatee@jiathis.com",
  "gender": "Bigender",
  "ip_address": "39.104.120.230"
}, {
  "id": 16,
  "first_name": "Reese",
  "last_name": "Richardot",
  "email": "rrichardotf@theatlantic.com",
  "gender": "Male",
  "ip_address": "211.215.173.233"
}, {
  "id": 17,
  "first_name": "Aldous",
  "last_name": "Hutcheon",
  "email": "ahutcheong@ucoz.com",
  "gender": "Male",
  "ip_address": "222.249.92.145"
}, {
  "id": 18,
  "first_name": "Fergus",
  "last_name": "Douglass",
  "email": "fdouglassh@liveinternet.ru",
  "gender": "Male",
  "ip_address": "17.235.209.11"
}, {
  "id": 19,
  "first_name": "Timmie",
  "last_name": "Sebert",
  "email": "tseberti@google.com.br",
  "gender": "Agender",
  "ip_address": "39.129.136.179"
}, {
  "id": 20,
  "first_name": "Shaina",
  "last_name": "De Dantesie",
  "email": "sdedantesiej@cbsnews.com",
  "gender": "Female",
  "ip_address": "1.150.30.20"
}, {
  "id": 21,
  "first_name": "Bard",
  "last_name": "Garrish",
  "email": "bgarrishk@prweb.com",
  "gender": "Male",
  "ip_address": "20.166.14.93"
}, {
  "id": 22,
  "first_name": "Fredia",
  "last_name": "Brade",
  "email": "fbradel@jiathis.com",
  "gender": "Female",
  "ip_address": "235.109.171.237"
}, {
  "id": 23,
  "first_name": "Neal",
  "last_name": "Brader",
  "email": "nbraderm@umn.edu",
  "gender": "Male",
  "ip_address": "94.123.188.62"
}, {
  "id": 24,
  "first_name": "Trina",
  "last_name": "Tredgold",
  "email": "ttredgoldn@zdnet.com",
  "gender": "Female",
  "ip_address": "138.133.60.54"
}, {
  "id": 25,
  "first_name": "Maddie",
  "last_name": "Van der Beken",
  "email": "mvanderbekeno@google.co.uk",
  "gender": "Female",
  "ip_address": "184.16.242.194"
}, {
  "id": 26,
  "first_name": "Upton",
  "last_name": "Gaymer",
  "email": "ugaymerp@cbslocal.com",
  "gender": "Male",
  "ip_address": "97.97.161.208"
}, {
  "id": 27,
  "first_name": "Roma",
  "last_name": "Weatherdon",
  "email": "rweatherdonq@yolasite.com",
  "gender": "Polygender",
  "ip_address": "58.178.227.2"
}, {
  "id": 28,
  "first_name": "Bealle",
  "last_name": "Wanka",
  "email": "bwankar@hud.gov",
  "gender": "Male",
  "ip_address": "87.21.11.106"
}, {
  "id": 29,
  "first_name": "Aggi",
  "last_name": "Threlfall",
  "email": "athrelfalls@ask.com",
  "gender": "Female",
  "ip_address": "55.167.178.166"
}, {
  "id": 30,
  "first_name": "Toiboid",
  "last_name": "Mancer",
  "email": "tmancert@about.com",
  "gender": "Male",
  "ip_address": "26.18.159.137"
}, {
  "id": 31,
  "first_name": "Dorey",
  "last_name": "Heaps",
  "email": "dheapsu@prnewswire.com",
  "gender": "Female",
  "ip_address": "183.16.185.47"
}, {
  "id": 32,
  "first_name": "Kenton",
  "last_name": "Reynold",
  "email": "kreynoldv@ft.com",
  "gender": "Male",
  "ip_address": "70.140.7.138"
}, {
  "id": 33,
  "first_name": "Sophia",
  "last_name": "Woloschin",
  "email": "swoloschinw@businessinsider.com",
  "gender": "Female",
  "ip_address": "103.60.136.155"
}, {
  "id": 34,
  "first_name": "Ronny",
  "last_name": "Izard",
  "email": "rizardx@blogs.com",
  "gender": "Male",
  "ip_address": "45.59.164.6"
}, {
  "id": 35,
  "first_name": "Claudina",
  "last_name": "Charlo",
  "email": "ccharloy@godaddy.com",
  "gender": "Female",
  "ip_address": "26.235.39.148"
}, {
  "id": 36,
  "first_name": "Fran",
  "last_name": "Bandt",
  "email": "fbandtz@walmart.com",
  "gender": "Male",
  "ip_address": "203.148.105.212"
}, {
  "id": 37,
  "first_name": "Harriot",
  "last_name": "Buglar",
  "email": "hbuglar10@imdb.com",
  "gender": "Female",
  "ip_address": "2.117.146.148"
}, {
  "id": 38,
  "first_name": "Rozele",
  "last_name": "Butting",
  "email": "rbutting11@washington.edu",
  "gender": "Female",
  "ip_address": "89.241.43.180"
}, {
  "id": 39,
  "first_name": "Devon",
  "last_name": "Bolletti",
  "email": "dbolletti12@parallels.com",
  "gender": "Female",
  "ip_address": "188.4.114.211"
}, {
  "id": 40,
  "first_name": "Karrah",
  "last_name": "Nettle",
  "email": "knettle13@goo.gl",
  "gender": "Female",
  "ip_address": "202.251.123.26"
}, {
  "id": 41,
  "first_name": "Karalynn",
  "last_name": "Braysher",
  "email": "kbraysher14@4shared.com",
  "gender": "Female",
  "ip_address": "63.27.26.192"
}, {
  "id": 42,
  "first_name": "Dasie",
  "last_name": "Parsand",
  "email": "dparsand15@stumbleupon.com",
  "gender": "Female",
  "ip_address": "146.141.32.163"
}, {
  "id": 43,
  "first_name": "Nickey",
  "last_name": "Deerr",
  "email": "ndeerr16@imdb.com",
  "gender": "Male",
  "ip_address": "168.253.123.196"
}, {
  "id": 44,
  "first_name": "Nelli",
  "last_name": "Loadman",
  "email": "nloadman17@latimes.com",
  "gender": "Female",
  "ip_address": "105.96.9.10"
}, {
  "id": 45,
  "first_name": "Rossy",
  "last_name": "Nurcombe",
  "email": "rnurcombe18@google.com.hk",
  "gender": "Male",
  "ip_address": "164.52.155.106"
}, {
  "id": 46,
  "first_name": "Nickey",
  "last_name": "Stileman",
  "email": "nstileman19@walmart.com",
  "gender": "Male",
  "ip_address": "64.237.57.189"
}, {
  "id": 47,
  "first_name": "Iago",
  "last_name": "Marlin",
  "email": "imarlin1a@furl.net",
  "gender": "Male",
  "ip_address": "117.156.65.185"
}, {
  "id": 48,
  "first_name": "Kingsly",
  "last_name": "Hay",
  "email": "khay1b@people.com.cn",
  "gender": "Male",
  "ip_address": "41.113.7.105"
}, {
  "id": 49,
  "first_name": "Winfred",
  "last_name": "Botger",
  "email": "wbotger1c@t.co",
  "gender": "Male",
  "ip_address": "196.136.75.46"
}, {
  "id": 50,
  "first_name": "Jeni",
  "last_name": "Vela",
  "email": "jvela1d@1und1.de",
  "gender": "Female",
  "ip_address": "102.118.213.73"
}, {
  "id": 51,
  "first_name": "Kalvin",
  "last_name": "Jahnel",
  "email": "kjahnel1e@addtoany.com",
  "gender": "Male",
  "ip_address": "3.76.253.23"
}, {
  "id": 52,
  "first_name": "Harmonie",
  "last_name": "Osgardby",
  "email": "hosgardby1f@naver.com",
  "gender": "Female",
  "ip_address": "115.253.181.207"
}, {
  "id": 53,
  "first_name": "Evonne",
  "last_name": "Hardson",
  "email": "ehardson1g@i2i.jp",
  "gender": "Female",
  "ip_address": "4.216.103.64"
}, {
  "id": 54,
  "first_name": "Hersch",
  "last_name": "Brougham",
  "email": "hbrougham1h@cocolog-nifty.com",
  "gender": "Male",
  "ip_address": "154.148.20.210"
}, {
  "id": 55,
  "first_name": "Brandea",
  "last_name": "Fleischmann",
  "email": "bfleischmann1i@cdbaby.com",
  "gender": "Female",
  "ip_address": "200.207.83.187"
}, {
  "id": 56,
  "first_name": "Masha",
  "last_name": "Drewes",
  "email": "mdrewes1j@bravesites.com",
  "gender": "Female",
  "ip_address": "27.149.45.115"
}, {
  "id": 57,
  "first_name": "Devland",
  "last_name": "Strowlger",
  "email": "dstrowlger1k@indiatimes.com",
  "gender": "Polygender",
  "ip_address": "114.178.141.234"
}, {
  "id": 58,
  "first_name": "Rozina",
  "last_name": "Elders",
  "email": "relders1l@digg.com",
  "gender": "Female",
  "ip_address": "121.24.223.24"
}, {
  "id": 59,
  "first_name": "Paige",
  "last_name": "Isaksen",
  "email": "pisaksen1m@behance.net",
  "gender": "Female",
  "ip_address": "20.90.178.172"
}, {
  "id": 60,
  "first_name": "Giffard",
  "last_name": "McCluney",
  "email": "gmccluney1n@tuttocitta.it",
  "gender": "Male",
  "ip_address": "106.217.209.137"
}, {
  "id": 61,
  "first_name": "Gamaliel",
  "last_name": "Ortes",
  "email": "gortes1o@naver.com",
  "gender": "Male",
  "ip_address": "1.19.50.49"
}, {
  "id": 62,
  "first_name": "Clive",
  "last_name": "Fodden",
  "email": "cfodden1p@t.co",
  "gender": "Male",
  "ip_address": "223.74.118.57"
}, {
  "id": 63,
  "first_name": "Jens",
  "last_name": "MacCarlich",
  "email": "jmaccarlich1q@hud.gov",
  "gender": "Male",
  "ip_address": "25.44.149.43"
}, {
  "id": 64,
  "first_name": "Ella",
  "last_name": "Bamlett",
  "email": "ebamlett1r@msu.edu",
  "gender": "Female",
  "ip_address": "17.19.97.178"
}, {
  "id": 65,
  "first_name": "Wit",
  "last_name": "Grisdale",
  "email": "wgrisdale1s@cbc.ca",
  "gender": "Bigender",
  "ip_address": "149.236.96.240"
}, {
  "id": 66,
  "first_name": "Olag",
  "last_name": "Colling",
  "email": "ocolling1t@xing.com",
  "gender": "Male",
  "ip_address": "210.190.139.181"
}, {
  "id": 67,
  "first_name": "Dannel",
  "last_name": "Heamus",
  "email": "dheamus1u@sciencedaily.com",
  "gender": "Male",
  "ip_address": "63.204.140.248"
}, {
  "id": 68,
  "first_name": "Gertrudis",
  "last_name": "Ruger",
  "email": "gruger1v@springer.com",
  "gender": "Female",
  "ip_address": "243.167.11.64"
}, {
  "id": 69,
  "first_name": "Camilla",
  "last_name": "Bettinson",
  "email": "cbettinson1w@amazonaws.com",
  "gender": "Female",
  "ip_address": "225.221.153.164"
}, {
  "id": 70,
  "first_name": "Kort",
  "last_name": "Batrop",
  "email": "kbatrop1x@sbwire.com",
  "gender": "Male",
  "ip_address": "247.14.144.15"
}, {
  "id": 71,
  "first_name": "Nerissa",
  "last_name": "Gregor",
  "email": "ngregor1y@shop-pro.jp",
  "gender": "Female",
  "ip_address": "85.45.149.178"
}, {
  "id": 72,
  "first_name": "Constantino",
  "last_name": "Seedull",
  "email": "cseedull1z@cornell.edu",
  "gender": "Male",
  "ip_address": "31.123.4.86"
}, {
  "id": 73,
  "first_name": "Margret",
  "last_name": "Hardistry",
  "email": "mhardistry20@goodreads.com",
  "gender": "Female",
  "ip_address": "31.127.120.220"
}, {
  "id": 74,
  "first_name": "Brandice",
  "last_name": "Gartside",
  "email": "bgartside21@yahoo.com",
  "gender": "Female",
  "ip_address": "123.81.94.40"
}, {
  "id": 75,
  "first_name": "Dimitri",
  "last_name": "Smaile",
  "email": "dsmaile22@wikia.com",
  "gender": "Male",
  "ip_address": "21.64.166.239"
}, {
  "id": 76,
  "first_name": "Wilbur",
  "last_name": "Corbie",
  "email": "wcorbie23@a8.net",
  "gender": "Male",
  "ip_address": "202.160.225.184"
}, {
  "id": 77,
  "first_name": "Emelda",
  "last_name": "Setchell",
  "email": "esetchell24@seattletimes.com",
  "gender": "Female",
  "ip_address": "31.255.114.68"
}, {
  "id": 78,
  "first_name": "Marcelo",
  "last_name": "Treend",
  "email": "mtreend25@yolasite.com",
  "gender": "Male",
  "ip_address": "237.192.114.217"
}, {
  "id": 79,
  "first_name": "Lorne",
  "last_name": "Forster",
  "email": "lforster26@lulu.com",
  "gender": "Genderqueer",
  "ip_address": "10.188.59.147"
}, {
  "id": 80,
  "first_name": "Rockwell",
  "last_name": "Asser",
  "email": "rasser27@webnode.com",
  "gender": "Male",
  "ip_address": "71.203.235.30"
}, {
  "id": 81,
  "first_name": "Faulkner",
  "last_name": "Sorley",
  "email": "fsorley28@va.gov",
  "gender": "Male",
  "ip_address": "55.168.174.1"
}, {
  "id": 82,
  "first_name": "Gilli",
  "last_name": "Mendenhall",
  "email": "gmendenhall29@addthis.com",
  "gender": "Female",
  "ip_address": "168.250.28.254"
}, {
  "id": 83,
  "first_name": "Hobey",
  "last_name": "Vaen",
  "email": "hvaen2a@theatlantic.com",
  "gender": "Male",
  "ip_address": "233.155.157.6"
}, {
  "id": 84,
  "first_name": "Aida",
  "last_name": "Samudio",
  "email": "asamudio2b@washington.edu",
  "gender": "Female",
  "ip_address": "145.208.79.78"
}, {
  "id": 85,
  "first_name": "Robina",
  "last_name": "Neicho",
  "email": "rneicho2c@list-manage.com",
  "gender": "Genderqueer",
  "ip_address": "255.235.12.42"
}, {
  "id": 86,
  "first_name": "Palmer",
  "last_name": "Piell",
  "email": "ppiell2d@latimes.com",
  "gender": "Male",
  "ip_address": "15.225.104.174"
}, {
  "id": 87,
  "first_name": "Erik",
  "last_name": "Rame",
  "email": "erame2e@reuters.com",
  "gender": "Male",
  "ip_address": "197.73.172.49"
}, {
  "id": 88,
  "first_name": "Fremont",
  "last_name": "Vaughton",
  "email": "fvaughton2f@thetimes.co.uk",
  "gender": "Male",
  "ip_address": "171.125.14.160"
}, {
  "id": 89,
  "first_name": "Trueman",
  "last_name": "Vogl",
  "email": "tvogl2g@weebly.com",
  "gender": "Male",
  "ip_address": "41.190.233.160"
}, {
  "id": 90,
  "first_name": "Red",
  "last_name": "McNess",
  "email": "rmcness2h@spiegel.de",
  "gender": "Male",
  "ip_address": "237.196.93.152"
}, {
  "id": 91,
  "first_name": "Myrtle",
  "last_name": "Crop",
  "email": "mcrop2i@biglobe.ne.jp",
  "gender": "Female",
  "ip_address": "242.64.120.87"
}, {
  "id": 92,
  "first_name": "Cam",
  "last_name": "Todarini",
  "email": "ctodarini2j@ibm.com",
  "gender": "Male",
  "ip_address": "78.65.228.6"
}, {
  "id": 93,
  "first_name": "Augustine",
  "last_name": "Crippin",
  "email": "acrippin2k@ebay.co.uk",
  "gender": "Male",
  "ip_address": "178.213.221.157"
}, {
  "id": 94,
  "first_name": "Lynnet",
  "last_name": "Brunke",
  "email": "lbrunke2l@amazon.co.jp",
  "gender": "Female",
  "ip_address": "53.11.184.24"
}, {
  "id": 95,
  "first_name": "Christiane",
  "last_name": "Chetter",
  "email": "cchetter2m@meetup.com",
  "gender": "Female",
  "ip_address": "62.82.180.22"
}, {
  "id": 96,
  "first_name": "Amie",
  "last_name": "Destouche",
  "email": "adestouche2n@house.gov",
  "gender": "Female",
  "ip_address": "233.47.88.49"
}, {
  "id": 97,
  "first_name": "Austen",
  "last_name": "Locket",
  "email": "alocket2o@51.la",
  "gender": "Male",
  "ip_address": "161.214.153.78"
}, {
  "id": 98,
  "first_name": "Kissie",
  "last_name": "Fernandez",
  "email": "kfernandez2p@va.gov",
  "gender": "Female",
  "ip_address": "28.165.83.142"
}, {
  "id": 99,
  "first_name": "Timoteo",
  "last_name": "Cramp",
  "email": "tcramp2q@xing.com",
  "gender": "Male",
  "ip_address": "8.238.83.133"
}, {
  "id": 100,
  "first_name": "Appolonia",
  "last_name": "Jevon",
  "email": "ajevon2r@dell.com",
  "gender": "Female",
  "ip_address": "22.72.183.15"
}]

# templist = []
#
# for a in User_data:
# 	templist.append(dict( first_name = a["first_name"]  , last_name = a["last_name"]  , email = a["email"]))
# print(templist)

# count = 0
# while count < len(User_data):
# 	if User_data[count]['id'] == 47:
# 		print(User_data[count])
# 	count += 1